spring:
  application:
    name: lovable-clone
    description: this is application

  datasource:
    url: jdbc:postgresql://localhost:9000/testDB
    username: testUser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc: time_zone=Asia/Kolkata

jwt:
  secret-key: as9b7aodlbjfkluosfd789ujeklfnlsduf90b8ha908w74tuqijvlckajdl

stripe:
  api:
    secret: sk_test_51So1yVAZtdRpxJsnkXg7ddVlYwU63vKuv2gekt7hezFL7PE68QsENyrMr2tjjIMUe1ANqkO7M7UMEuqAgq0kxLdV00SYVwNFRx
  webhook:
    secret: whsec_55fceb6140aa36aaa94f14fd170eb57cfb9a0d4fabacabf17dcb7791b7994a72
client.url: http://localhost:8080